services:
  - type: web
    name: footprint-app
    runtime: node
    rootDir: artifacts/footprint-pdf
    buildCommand: npm install -g pnpm && pnpm install && PORT=3000 pnpm run build
    startCommand: node --enable-source-maps dist/server/index.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
